repos:
  - repo: https://github.com/Exabyte-io/pre-commit-hooks
    rev: 2023.9.13
    hooks:
      - id: black
      - id: ruff
      - id: isort
      - id: end-of-file-fixer
      - id: trailing-whitespace
